# Generated by Django 5.0.1 on 2024-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='repassword',
            field=models.CharField(default='', max_length=200),
        ),
    ]
