# Generated by Django 5.0.1 on 2024-03-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0002_register_repassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='filedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='media/')),
            ],
        ),
    ]
