# Generated by Django 5.0.1 on 2024-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0004_adminregister_delete_filedata_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliderdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('background_img', models.ImageField(upload_to='background_images/')),
            ],
        ),
    ]
