# Generated by Django 5.0.1 on 2024-05-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0008_alter_offerdata_offer_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_cat', models.CharField(max_length=200)),
            ],
        ),
    ]
