# Generated by Django 5.0.1 on 2024-05-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0009_categorydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydata',
            old_name='our_cat',
            new_name='ourcat',
        ),
    ]
