# Generated by Django 5.0.1 on 2024-05-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0010_rename_our_cat_categorydata_ourcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_img', models.ImageField(blank=True, null=True, upload_to='slider-media/')),
                ('post_title', models.CharField(max_length=200)),
                ('post_date', models.DateField()),
                ('post_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
