# Generated by Django 5.0.1 on 2024-05-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0011_blogdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='categories',
            field=models.ManyToManyField(to='myadminapp.categorydata'),
        ),
    ]
