# Generated by Django 5.0.1 on 2024-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0012_blogdata_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='auth_name',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
