# Generated by Django 5.0.1 on 2024-06-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0013_blogdata_auth_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='about_des',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
