# Generated by Django 5.0.1 on 2024-06-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadminapp', '0014_blogdata_about_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='post_description',
            field=models.CharField(max_length=10000),
        ),
    ]
